import { useState } from "react";
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";
import { resetAutomation, scanAutomation, setAutomation } from "../api/automation";
import MetricCard from "./MetricCard";
export default function PaperAutomationPanel({ data, performance, onRefresh }) {
 const [busy,setBusy]=useState(false); const account=data?.account; const validation=data?.validation||{}; const enabled=Boolean(data?.enabled);
 const act=async(fn)=>{setBusy(true);try{await fn();await onRefresh();}catch(e){alert(e.message)}finally{setBusy(false)}};
 const curve=(performance||[]).map(x=>({date:x.tradingDate,pnl:Number(x.pnl||0),equity:Number(x.finalEquity||0)}));
 return <section className="panel automation-panel"><div className="panel-header"><div><span className="eyebrow">Daily automation</span><h2>NIFTY 50 paper trader</h2><p className="muted">₹100,000 reset at 09:15 IST · max 5 positions · no overnight positions.</p></div><div className={`automation-status ${enabled?"on":"off"}`}>{enabled?"AUTOMATED PAPER ON":"AUTOMATED PAPER OFF"}</div></div><div className="automation-actions"><button className={`button ${enabled?"secondary":"primary"}`} disabled={busy} onClick={()=>act(()=>setAutomation(!enabled))}>{enabled?"Pause automation":"Start automated paper trading"}</button><button className="button ghost" disabled={busy} onClick={()=>act(resetAutomation)}>Reset today's account</button><button className="button ghost" disabled={busy} onClick={()=>act(scanAutomation)}>Run scan now</button></div><div className="metric-grid"><MetricCard label="Paper equity" value={`₹${Number(account?.equity??100000).toFixed(2)}`} hint="Today's account"/><MetricCard label="Daily P&L" value={`₹${Number(account?.realizedPnl||0).toFixed(2)}`} tone={Number(account?.realizedPnl||0)>=0?"positive":"negative"}/><MetricCard label="Profit factor" value={Number(validation.profitFactor||0).toFixed(2)} hint="20-day gate"/><MetricCard label="Max drawdown" value={`${Number(validation.maxDrawdownPercent||0).toFixed(2)}%`} hint="Must stay below 15%"/></div><div className="validation-strip"><strong>Live validation:</strong> {validation.eligible?"Eligible — all three thresholds passed.":`Locked — ${validation.days||0}/20 days; PF ${Number(validation.profitFactor||0).toFixed(2)}; DD ${Number(validation.maxDrawdownPercent||0).toFixed(2)}%; expectancy ${Number(validation.expectancy||0).toFixed(2)}.`}</div><div className="automation-chart"><h3>Capital curve</h3>{curve.length?<ResponsiveContainer width="100%" height={240}><LineChart data={curve}><XAxis dataKey="date"/><YAxis/><Tooltip formatter={(v)=>[`₹${Number(v).toFixed(2)}`]}/><Line type="monotone" dataKey="equity" dot={false}/></LineChart></ResponsiveContainer>:<p className="muted">No completed automated days yet.</p>}</div></section>;
}
