import { env } from "../config/env";
import { NIFTY50_SYMBOLS } from "../config/nifty50";
import { AutomationConfigModel } from "../models/automation-config.model";
import { DailyPerformanceModel } from "../models/daily-performance.model";
import { PaperAccountModel } from "../models/paper-account.model";
import { PositionModel } from "../models/position.model";
import { TradeModel } from "../models/trade.model";
import { UserDocument, UserModel } from "../models/user.model";
import { brokerService } from "./brokers/broker.service";
import { StrategyService } from "./strategy.service";
import { AppError } from "../utils/errors";
const TZ="Asia/Kolkata";
const dateKey=(d=new Date())=>new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit"}).format(d);
const timeKey=(d=new Date())=>new Intl.DateTimeFormat("en-GB",{timeZone:TZ,hour:"2-digit",minute:"2-digit",hour12:false}).format(d);
const NO_BROKER_SESSION="Zerodha session is not connected; automated paper trading needs it for NIFTY 50 market data";
export class PaperAutomationService {
 constructor(private strategy=new StrategyService()){}
 async getOrCreateConfig(user:UserDocument){return AutomationConfigModel.findOneAndUpdate({userId:user._id},{$setOnInsert:{userId:user._id,enabled:env.paperAutomationEnabled,universe:"NIFTY50",initialCapital:env.paperInitialCapital,riskPerTradePercent:env.paperRiskPerTradePercent,rewardRiskRatio:env.paperRewardRiskRatio,maxPositions:env.paperMaxPositions,stopDistancePercent:env.paperStopDistancePercent,vwapDeviationPercent:env.paperVwapDeviationPercent,scanIntervalMinutes:env.paperScanIntervalMinutes,entryStartTime:env.paperEntryStartTime}},{upsert:true,new:true,setDefaultsOnInsert:true});}
 async setEnabled(user:UserDocument,enabled:boolean){const c=await this.getOrCreateConfig(user);c.enabled=enabled;await c.save();return this.snapshot(user);}
 async resetDay(user:UserDocument,force=false){const c=await this.getOrCreateConfig(user),today=dateKey();if(!force&&c.lastResetDate===today)return PaperAccountModel.findOne({userId:user._id,tradingDate:today});if(force){await PaperAccountModel.deleteOne({userId:user._id,tradingDate:today});await DailyPerformanceModel.deleteOne({userId:user._id,tradingDate:today});}const previous=await PaperAccountModel.findOne({userId:user._id,status:"open",tradingDate:{$ne:today}}).sort({tradingDate:-1});if(previous){for(const p of await PositionModel.find({userId:user._id,automated:true,quantity:{$ne:0}}))await this.closePosition(user,previous,p.symbol,p.markPrice||p.averageEntryPrice,"daily_reset");previous.status="closed";previous.closedAt=new Date();await this.recompute(user,previous);await this.updateDailyPerformance(user,previous,"closed");}else{await PositionModel.deleteMany({userId:user._id,automated:true,quantity:{$ne:0}});}await PaperAccountModel.updateMany({userId:user._id,status:"open",tradingDate:{$ne:today}},{$set:{status:"closed",closedAt:new Date()}});const account=await PaperAccountModel.findOneAndUpdate({userId:user._id,tradingDate:today},{$setOnInsert:{userId:user._id,tradingDate:today,initialCapital:env.paperInitialCapital,cash:env.paperInitialCapital,equity:env.paperInitialCapital,realizedPnl:0,unrealizedPnl:0,peakEquity:env.paperInitialCapital,maxDrawdownPercent:0,status:"open",resetAt:new Date()}},{upsert:true,new:true,setDefaultsOnInsert:true});c.lastResetDate=today;c.lastScanAt=undefined;await c.save();return account;}
 private account(user:UserDocument,date=dateKey()){return PaperAccountModel.findOne({userId:user._id,tradingDate:date});}
 async scanUser(user:UserDocument){const c=await this.getOrCreateConfig(user);if(!c.enabled||user.tradingMode!=="paper")return {skipped:true,reason:"automation disabled or account is not paper"};const now=new Date();if(timeKey(now)<c.entryStartTime||timeKey(now)>=env.paperMarketCloseTime)return {skipped:true,reason:"outside entry window"};if(!(await brokerService.hasSession(user)))return {skipped:true,reason:NO_BROKER_SESSION};let a=await this.account(user);if(!a)a=await this.resetDay(user);if(!a)throw new AppError(500,"Daily paper account unavailable");const open=await PositionModel.find({userId:user._id,automated:true,quantity:{$ne:0}});if(open.length>=c.maxPositions)return {skipped:true,reason:"max simultaneous positions reached"};const token=await brokerService.token(user);const map=await brokerService.getNifty50InstrumentMap(user,[...NIFTY50_SYMBOLS],token);let entries=0;for(const symbol of NIFTY50_SYMBOLS){if(open.length+entries>=c.maxPositions)break;const instrumentToken=map.get(symbol);if(!instrumentToken)continue;const bars=await brokerService.getIntradayBars(user,instrumentToken,token);const s=this.strategy.generateSignal(symbol,bars,{vwapDeviationPercent:c.vwapDeviationPercent,rewardRiskRatio:c.rewardRiskRatio,stopDistancePercent:c.stopDistancePercent});if(s.action==="hold"||!s.entryPrice||!s.stopPrice||!s.targetPrice)continue;
  // Any non-zero position (manual or automated) blocks entry: positions are unique per user+symbol.
  if(await PositionModel.findOne({userId:user._id,symbol,quantity:{$ne:0}}))continue;const riskBudget=a.initialCapital*c.riskPerTradePercent/100,riskPerShare=Math.abs(s.entryPrice-s.stopPrice);if(!(riskPerShare>0))continue;const qty=Math.floor(riskBudget/riskPerShare);if(qty<=0)continue;const affordable=s.action==="buy"?Math.floor(a.cash/s.entryPrice):qty;const finalQty=Math.min(qty,affordable);if(finalQty<=0)continue;await this.open(user,a,symbol,s.action,finalQty,s.entryPrice,s.stopPrice,s.targetPrice,s.reason);entries++;}c.lastScanAt=now;await c.save();await this.mark(user,a);return {scanned:NIFTY50_SYMBOLS.length,entries,tradingDate:a.tradingDate};}
 private async open(user:UserDocument,a:any,symbol:string,side:"buy"|"sell",qty:number,price:number,stop:number,target:number,reason:string){const signed=side==="buy"?qty:-qty,notional=price*qty;if(side==="buy")a.cash-=notional;else a.cash+=notional;const trade=await TradeModel.create({userId:user._id,symbol,side,quantity:qty,requestedPrice:price,fillPrice:price,notional,status:"filled",strategy:"nifty50-15m-breakout-vwap",automated:true,tradingDate:a.tradingDate,stopLossPrice:stop,targetPrice:target,entryReason:reason,realizedPnl:0,submittedAt:new Date(),filledAt:new Date()});await PositionModel.findOneAndUpdate({userId:user._id,symbol},{$set:{userId:user._id,symbol,quantity:signed,averageEntryPrice:price,markPrice:price,unrealizedPnl:0,realizedPnl:0,stopLossPrice:stop,targetPrice:target,automated:true,tradingDate:a.tradingDate,entryTradeId:trade._id,openedAt:new Date()}},{upsert:true,new:true});await a.save();}
 async manageOpenPositions(user:UserDocument){const a=await this.account(user);if(!a||a.status!=="open")return;if(!(await brokerService.hasSession(user)))return;const positions=await PositionModel.find({userId:user._id,automated:true,quantity:{$ne:0}});if(!positions.length)return;const prices=await brokerService.getLastPrices(user,positions.map(p=>p.symbol));for(const p of positions){const latest=prices.get(p.symbol);if(!latest)continue;const stop=p.quantity>0?latest<=Number(p.stopLossPrice):latest>=Number(p.stopLossPrice),target=p.quantity>0?latest>=Number(p.targetPrice):latest<=Number(p.targetPrice);if(stop||target)await this.closePosition(user,a,p.symbol,latest,stop?"stop_loss":"target");else{p.markPrice=latest;p.unrealizedPnl=(latest-p.averageEntryPrice)*p.quantity;await p.save();}}await this.mark(user,a);}
 async closePosition(user:UserDocument,a:any,symbol:string,price:number,reason:string){const p=await PositionModel.findOne({userId:user._id,symbol,automated:true,quantity:{$ne:0}});if(!p)return;const qty=Math.abs(p.quantity),side=p.quantity>0?"sell":"buy",pnl=p.quantity>0?(price-p.averageEntryPrice)*qty:(p.averageEntryPrice-price)*qty;if(side==="sell")a.cash+=price*qty;else a.cash-=price*qty;a.realizedPnl+=pnl;await TradeModel.create({userId:user._id,symbol,side,quantity:qty,requestedPrice:price,fillPrice:price,notional:price*qty,status:"filled",strategy:"nifty50-15m-breakout-vwap",automated:true,tradingDate:a.tradingDate,exitReason:reason,realizedPnl:pnl,submittedAt:new Date(),filledAt:new Date()});await p.deleteOne();await a.save();}
 async closeAll(user:UserDocument,reason="market_close",finalize=false){const a=await this.account(user);if(!a)return;const positions=await PositionModel.find({userId:user._id,automated:true,quantity:{$ne:0}});
  // Exit at a fresh quote when possible; the stored mark can be several minutes old.
  let prices=new Map<string,number>();if(positions.length&&(await brokerService.hasSession(user))){try{prices=await brokerService.getLastPrices(user,positions.map(p=>p.symbol));}catch(e){console.error("Paper close: quote fetch failed, using last mark prices",e);}}for(const p of positions)await this.closePosition(user,a,p.symbol,prices.get(p.symbol)||p.markPrice||p.averageEntryPrice,reason);if(finalize){a.status="closed";a.closedAt=new Date();}await this.recompute(user,a);await this.updateDailyPerformance(user,a,finalize?"closed":"running");}
 // Equity is cash plus the signed market value of open positions (short proceeds sit in cash).
 private async recompute(user:UserDocument,a:any){const ps=await PositionModel.find({userId:user._id,automated:true,quantity:{$ne:0}});a.unrealizedPnl=ps.reduce((s,p)=>s+Number(p.unrealizedPnl||0),0);a.equity=a.cash+ps.reduce((s,p)=>s+Number(p.quantity||0)*Number(p.markPrice||p.averageEntryPrice||0),0);a.peakEquity=Math.max(a.peakEquity,a.equity);a.maxDrawdownPercent=Math.max(a.maxDrawdownPercent,a.peakEquity?((a.peakEquity-a.equity)/a.peakEquity)*100:0);await a.save();}
 private async mark(user:UserDocument,a:any){await this.recompute(user,a);await this.updateDailyPerformance(user,a,"running");}
 async updateDailyPerformance(user:UserDocument,a:any,status:"running"|"closed"|"no_data"){const ts=await TradeModel.find({userId:user._id,tradingDate:a.tradingDate,automated:true,realizedPnl:{$ne:0}}).select("realizedPnl").lean();const pnls=ts.map((t:any)=>Number(t.realizedPnl||0)),wins=pnls.filter(p=>p>0),losses=pnls.filter(p=>p<0),gp=wins.reduce((x,y)=>x+y,0),gl=Math.abs(losses.reduce((x,y)=>x+y,0)),count=pnls.length, pf=gl?gp/gl:(gp?Infinity:0),exp=count?pnls.reduce((x,y)=>x+y,0)/count:0;const prev=await DailyPerformanceModel.find({userId:user._id,tradingDate:{$ne:a.tradingDate}}).sort({tradingDate:-1}).limit(19).lean();const last20=[...prev,{pnl:a.realizedPnl}];const positive=last20.length===20&&last20.reduce((s,d:any)=>s+Number(d.pnl||0),0)/20>0;await DailyPerformanceModel.findOneAndUpdate({userId:user._id,tradingDate:a.tradingDate},{$set:{userId:user._id,tradingDate:a.tradingDate,initialCapital:a.initialCapital,finalEquity:a.equity,pnl:a.realizedPnl+a.unrealizedPnl,returnPercent:(a.equity-a.initialCapital)/a.initialCapital*100,tradeCount:count,winningTrades:wins.length,losingTrades:losses.length,winRate:count?wins.length/count*100:0,grossProfit:gp,grossLoss:gl,profitFactor:pf,maxDrawdownPercent:a.maxDrawdownPercent,expectancy:exp,positiveExpectancy20d:positive,automationStatus:status}},{upsert:true,new:true});}
 async validation(user:UserDocument){const minPf=env.liveMinProfitFactor,maxDdLimit=env.liveMaxPaperDrawdownPercent;const days=await DailyPerformanceModel.find({userId:user._id}).sort({tradingDate:-1}).limit(20).lean(),pnls=days.map(d=>Number(d.pnl||0)),gp=pnls.filter(p=>p>0).reduce((a,b)=>a+b,0),gl=Math.abs(pnls.filter(p=>p<0).reduce((a,b)=>a+b,0)),pf=gl?gp/gl:(gp?Infinity:0);let equity=env.paperInitialCapital,peak=env.paperInitialCapital,maxDd=0;for(const p of [...pnls].reverse()){equity+=p;peak=Math.max(peak,equity);maxDd=Math.max(maxDd,peak?((peak-equity)/peak)*100:0);}const expectancy=pnls.length===20?pnls.reduce((a,b)=>a+b,0)/20:0;return {eligible:pnls.length===20&&pf>minPf&&maxDd<maxDdLimit&&expectancy>0,days:pnls.length,profitFactor:pf,maxDrawdownPercent:maxDd,expectancy,thresholds:{profitFactor:`> ${minPf}`,maxDrawdownPercent:`< ${maxDdLimit}%`,positiveExpectancy20d:"> 0"}};}
 async snapshot(user:UserDocument){const c=await this.getOrCreateConfig(user),a=await this.account(user),positions=await PositionModel.find({userId:user._id,automated:true,quantity:{$ne:0}}).sort({symbol:1}).lean(),performance=a?await DailyPerformanceModel.findOne({userId:user._id,tradingDate:a.tradingDate}).lean():null;return {enabled:c.enabled,config:c,universe:c.universe,tradingDate:a?.tradingDate??dateKey(),account:a,positions,performance,validation:await this.validation(user)};}
 // Each user runs in isolation so one failure (e.g. an expired Zerodha token) doesn't stop the rest.
 private async forEachEnabledUser(label:string,fn:(u:UserDocument)=>Promise<unknown>){for(const u of await UserModel.find({tradingMode:"paper"})){try{const c=await this.getOrCreateConfig(u);if(c.enabled)await fn(u);}catch(e){console.error(`Paper automation ${label} failed for user ${u.id}`,e);}}}
 async resetEnabledUsers(){await this.forEachEnabledUser("reset",u=>this.resetDay(u));}
 async scanEnabledUsers(){await this.forEachEnabledUser("scan",async u=>{await this.manageOpenPositions(u);await this.scanUser(u);});}
 async closeAllUsers(){await this.forEachEnabledUser("close",u=>this.closeAll(u,"market_close",true));}
}
export const paperAutomationService=new PaperAutomationService();
