import { Request,Response } from "express";
import { AppError } from "../utils/errors";
import { TradingService } from "../services/trading.service";
import { validateLiveOrder } from "../services/live-risk.service";
import { brokerService } from "../services/brokers/broker.service";
import { OrderLogModel } from "../models/order-log.model";
const paper=new TradingService();
export async function place(req:Request,res:Response){if(!req.user)throw new AppError(401,"Authentication required");const b=req.body??{};if(req.user.tradingMode==="paper"){const result=await paper.placePaperOrder(req.user,{symbol:b.symbol,side:b.side,quantity:b.quantity,price:b.price,strategy:b.strategy});await OrderLogModel.create({userId:req.user._id,broker:"internal",mode:"paper",action:"place",symbol:String(b.symbol).toUpperCase(),side:String(b.side).toUpperCase(),quantity:Number(b.quantity),status:"filled",requestSummary:{symbol:b.symbol,side:b.side,quantity:b.quantity,price:b.price},responseSummary:{tradeId:result.trade.id}});return res.status(201).json({mode:"paper",...result});}await validateLiveOrder(req.user,{symbol:String(b.symbol),side:String(b.side).toUpperCase() as any,quantity:Number(b.quantity),price:Number(b.price),stopLossPrice:b.stopLossPrice===undefined?undefined:Number(b.stopLossPrice)});const input={exchange:String(b.exchange??"NSE"),tradingsymbol:String(b.symbol).toUpperCase(),transaction_type:String(b.side).toUpperCase() as any,quantity:Number(b.quantity),product:b.product??"MIS",order_type:b.orderType??"MARKET",price:b.price===undefined?undefined:Number(b.price),trigger_price:b.triggerPrice===undefined?undefined:Number(b.triggerPrice),validity:b.validity??"DAY",variety:b.variety??"regular",tag:b.tag};try{const result=await brokerService.place(req.user,input);await OrderLogModel.create({userId:req.user._id,broker:"zerodha",mode:"live",action:"place",symbol:input.tradingsymbol,side:input.transaction_type,quantity:input.quantity,orderType:input.order_type,variety:input.variety,brokerOrderId:result.orderId,status:"submitted",requestSummary:{...input},responseSummary:{orderId:result.orderId}});return res.status(201).json({mode:"live",...result,status:"submitted"});}catch(error:any){await OrderLogModel.create({userId:req.user._id,broker:"zerodha",mode:"live",action:"place",symbol:input.tradingsymbol,side:input.transaction_type,quantity:input.quantity,status:"error",requestSummary:{...input},errorMessage:error?.message});throw error;}}
export async function modify(req:Request,res:Response){if(!req.user)throw new AppError(401,"Authentication required");if(req.user.tradingMode!=="live")throw new AppError(403,"Order modification is only available in live mode");const orderId=String(req.params.orderId);const result=await brokerService.modify(req.user,String(req.body?.variety??"regular"),orderId,req.body?.params??{});await OrderLogModel.create({userId:req.user._id,broker:"zerodha",mode:"live",action:"modify",symbol:String(req.body?.symbol??"UNKNOWN").toUpperCase(),brokerOrderId:result.orderId,status:"submitted",requestSummary:{orderId,params:req.body?.params}});res.json({mode:"live",...result});}
export async function cancel(req:Request,res:Response){if(!req.user)throw new AppError(401,"Authentication required");if(req.user.tradingMode!=="live")throw new AppError(403,"Order cancellation is only available in live mode");const result=await brokerService.cancel(req.user,String(req.body?.variety??"regular"),String(req.params.orderId));await OrderLogModel.create({userId:req.user._id,broker:"zerodha",mode:"live",action:"cancel",symbol:String(req.body?.symbol??"UNKNOWN").toUpperCase(),brokerOrderId:result.orderId,status:"cancelled"});res.json({mode:"live",...result});}
